In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3555, 0.8087, 0.7751],
        [0.2345, 0.1840, 0.9670],
        [0.7784, 0.4358, 0.0931],
        [0.5234, 0.7243, 0.0056],
        [0.5482, 0.3293, 0.7113]])


In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4760, -0.5652, -0.8241],
        [-1.2591, -1.2068, -0.8467],
        [ 0.4726,  0.2915,  1.1904],
        [-0.3377, -0.7472, -0.5226],
        [ 2.0210, -0.3253,  0.1582]])


In [8]:
print(x.size()) #torchのサイズはタプル表現

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2220, -0.1879,  0.1348],
        [-0.7839, -0.3163, -0.5018],
        [ 0.6900,  0.3427,  1.3561],
        [ 0.5337, -0.6519, -0.4887],
        [ 2.7621, -0.0125,  0.9177]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.2220, -0.1879,  0.1348],
        [-0.7839, -0.3163, -0.5018],
        [ 0.6900,  0.3427,  1.3561],
        [ 0.5337, -0.6519, -0.4887],
        [ 2.7621, -0.0125,  0.9177]])


In [11]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.2220, -0.1879,  0.1348],
        [-0.7839, -0.3163, -0.5018],
        [ 0.6900,  0.3427,  1.3561],
        [ 0.5337, -0.6519, -0.4887],
        [ 2.7621, -0.0125,  0.9177]])


In [12]:
y.add_(x)
print(y)

tensor([[ 0.2220, -0.1879,  0.1348],
        [-0.7839, -0.3163, -0.5018],
        [ 0.6900,  0.3427,  1.3561],
        [ 0.5337, -0.6519, -0.4887],
        [ 2.7621, -0.0125,  0.9177]])


In [13]:
print(x[:, 1])

tensor([-0.5652, -1.2068,  0.2915, -0.7472, -0.3253])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4092])
-0.4091992676258087


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
